In [1]:
import pandas as pd

data = {
    "Name": ["Ayush", "Rahul", "Neha", "Priya"],
    "Age": [21, 22, 20, 23],
    "Marks": [85, 72, 90, 65],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks    City
0  Ayush   21     85   Delhi
1  Rahul   22     72  Mumbai
2   Neha   20     90   Delhi
3  Priya   23     65    Pune

In [3]:
type(df["Name"])

pandas.core.series.Series

In [6]:
df[["Name", "Marks"]]
df.head()

    Name  Age  Marks    City
0  Ayush   21     85   Delhi
1  Rahul   22     72  Mumbai
2   Neha   20     90   Delhi
3  Priya   23     65    Pune

In [5]:
df[df["Marks"]>80]

    Name  Age  Marks   City
0  Ayush   21     85  Delhi
2   Neha   20     90  Delhi

In [9]:
df[(df["Age"] >= 21) & (df["City"] == "Delhi")]

    Name  Age  Marks   City
0  Ayush   21     85  Delhi

In [15]:
df.sort_values(["City", "Marks"], ascending = [True, False])

    Name  Age  Marks    City
2   Neha   20     90   Delhi
0  Ayush   21     85   Delhi
1  Rahul   22     72  Mumbai
3  Priya   23     65    Pune

In [16]:
df.rename(columns = {"Marks" : "Obtained", "City" : "Location"})

    Name  Age  Obtained Location
0  Ayush   21        85    Delhi
1  Rahul   22        72   Mumbai
2   Neha   20        90    Delhi
3  Priya   23        65     Pune

In [19]:
data2= df.rename(columns ={"marks" : "Score"}, inplace = True)

None

In [20]:
import pandas as pd

data = {
    "Name": ["Ayush", "Rahul", "Neha", "Priya"],
    "Age": [21, 22, 20, 23],
    "Marks": [85, 72, 90, 65],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks    City
0  Ayush   21     85   Delhi
1  Rahul   22     72  Mumbai
2   Neha   20     90   Delhi
3  Priya   23     65    Pune

In [21]:
df.loc[0]

Name     Ayush
Age         21
Marks       85
City     Delhi
Name: 0, dtype: object

In [22]:
df.loc[0:2, ["Name", "Age"]]

    Name  Age
0  Ayush   21
1  Rahul   22
2   Neha   20

In [23]:
df.loc[df["Marks"]>80 , ["Name", "Marks"]]

    Name  Marks
0  Ayush     85
2   Neha     90

In [24]:
df.iloc[0]

Name     Ayush
Age         21
Marks       85
City     Delhi
Name: 0, dtype: object