In [ ]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('/results.csv',index_col='Respondent')
schema_df = pd.read_csv('/schema.csv', index_col='Column')
schema_df.head()

                                                  QuestionText
Column
Respondent   Randomized respondent ID number (not in order ...
MainBranch   Which of the following options best describes ...
Hobbyist                               Do you code as a hobby?
OpenSourcer        How often do you contribute to open source?
OpenSource   How do you feel about the quality of open sour...

In [18]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [22]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [24]:
df['ConvertedComp'].head(15)

Respondent
1          NaN
2          NaN
3       8820.0
4      61000.0
5          NaN
6     366420.0
7          NaN
8          NaN
9      95179.0
10     13293.0
11         NaN
12         NaN
13     90000.0
14     57060.0
15         NaN
Name: ConvertedComp, dtype: float64

In [25]:
df['ConvertedComp'].median()

57287.0

In [28]:
df.median(numeric_only=True)

CompTotal        61000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [29]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  3.946100e+04   3.937400e+04  45520.000000  35112.000000  55719.000000
mean   7.824409e+11   1.269161e+05     42.265751      5.109753     30.345006
std    8.729938e+13   2.836363e+05     41.874046      5.594624      9.176131
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.583900e+04     40.000000      2.000000     24.000000
50%    6.100000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.000000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [30]:
df['ConvertedComp'].count()

np.int64(39374)

In [31]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
62779    Yes
62780     No
62781    Yes
62782    Yes
62783    Yes
Name: Hobbyist, Length: 62382, dtype: object

In [32]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    50125
No     12257
Name: count, dtype: int64

In [33]:
df['SocialMedia']

Respondent
1          Twitter
2        Instagram
3           Reddit
4           Reddit
5         Facebook
           ...
62779      YouTube
62780     Facebook
62781     Facebook
62782      YouTube
62783          NaN
Name: SocialMedia, Length: 62382, dtype: object

In [35]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [36]:
df['SocialMedia'].value_counts()

SocialMedia
Reddit                      10210
YouTube                      9699
WhatsApp                     9441
Facebook                     9201
Twitter                      8088
Instagram                    4386
I don't use social media     3901
LinkedIn                     3113
WeChat 微信                     466
Snapchat                      426
VK ВКонта́кте                 401
Weibo 新浪微博                     42
Youku Tudou 优酷                 15
Hello                          14
Name: count, dtype: int64

In [37]:
df['SocialMedia'].value_counts(normalize= True)

SocialMedia
Reddit                      0.171877
YouTube                     0.163275
WhatsApp                    0.158931
Facebook                    0.154891
Twitter                     0.136155
Instagram                   0.073835
I don't use social media    0.065670
LinkedIn                    0.052405
WeChat 微信                   0.007845
Snapchat                    0.007171
VK ВКонта́кте               0.006751
Weibo 新浪微博                  0.000707
Youku Tudou 优酷              0.000253
Hello                       0.000236
Name: proportion, dtype: float64

In [38]:
df['Country'].value_counts()

Country
United States                       14723
India                                6395
Germany                              4131
United Kingdom                       4000
Canada                               2357
                                    ...
Saint Kitts and Nevis                   1
Malawi                                  1
Liberia                                 1
Saint Vincent and the Grenadines        1
San Marino                              1
Name: count, Length: 177, dtype: int64

In [39]:
country_grp = df.groupby(['Country'])

In [40]:
country_grp.get_group('India')

/tmp/ipykernel_1621/421256909.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62772,I am a developer by profession,No,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,10 to 19 employees,"Developer, back-end;Developer, desktop or ente...",12,24,10,Very dissatisfied,Neither satisfied nor dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,Industry that I'd be working in;Office environ...,I was preparing for a job search,INR,Indian rupee,NaN,Monthly,NaN,50.0,There is a schedule and/or spec (made by me or...,Not enough people for the workload;Time spent ...,"Less than half the time, but at least one day ...",Office,A little below average,No,NaN,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,C#;JavaScript;SQL,C#;JavaScript;SQL,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;jQuery,ASP.NET;jQuery,.NET,.NET;.NET Core,Notepad++;Visual Studio,Windows,I do not use containers,Not at all,Useful for immutable record keeping outside of...,Yes,Yes,Yes,WhatsApp,Online,Screen Name,2008,Daily or almost daily,Find answers to specific questions;Get a sense...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,38.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
62773,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, front-end;Developer, full-stack;Dev...",3,16,1,Slightly satisfied,Slightly satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Complete a take-home project;Interview with pe...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,INR,Indian rupee,950000.0,Yearly,13293.0,35.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Inadequate access...,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",10.0,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,HTML/CSS;JavaScript;TypeScript,Go;Python,Firebase;MongoDB;MySQL,NaN,Heroku;Linux;MacOS;Slack,AWS,Angular/Angular.js;Django;Flask;jQuery;Laravel...,Express,NaN,Node.js;React Native;TensorFlow;Torch/PyTorch,Visual Studio Code,MacOS,Development,Not at all,Useful across many domains and could change ma...,No,Yes,What?,Instagram,In real life (in person),Handle,2014,A few times per month or weekly,Find answers to specific questions,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,23.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
62776,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Completed an industry certification program (e...,100 to 499 employees,"Developer, front-end",6,20,4,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,No,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Remote w...,I heard about a job opportunity (from a recrui...,INR,Indian rupee,150000.0,Monthly,25188.0,NaN,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Not eno...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,Java;JavaScript;TypeScript,Bash/Shell/PowerShell;JavaScript;TypeScript,MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,MacOS;Windows,MacOS;Windows,Angular/Angular.js,Angular/Angular.js;React.js;Vue.js,Cordova;Node.js,Node.js;React Native,Eclipse;IntelliJ;Notepad++;Sublime Text;TextMa...,MacOS,I do not use containers,Not at all,NaN,Yes,SIGH,What?,WhatsApp,In real life (in person),NaN,2012,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
62777,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",India,"Yes, full-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,1,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,NaN,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,No,WhatsApp,Neither,UserID,2013,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Daily or almost daily,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,18.0,Man,NaN,NaN,NaN,NaN,NaN,NaN
62783,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,100 to 499 employees,"Developer, front-end;Developer, mobile",2,18,2,Slightly satisfied,Slightly satisfied,Not at all confident,No,No,I am actively looking for a job,1-2 years ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",INR,Indian rupee,37000.0,Monthly,6216.0,45.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Lack of...,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",10.0,"No, but I think we should",Not sure,I have a great deal of influence,C;C+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
filt = df['Country'] == 'India'
df[filt]['SocialMedia'].value_counts()

SocialMedia
WhatsApp                    2119
YouTube                     1291
LinkedIn                     672
Facebook                     606
Instagram                    571
Twitter                      383
Reddit                       334
I don't use social media     173
Snapchat                      15
VK ВКонта́кте                  4
Hello                          3
WeChat 微信                      3
Weibo 新浪微博                     1
Youku Tudou 优酷                 1
Name: count, dtype: int64

In [47]:
country_grp['SocialMedia'].value_counts(normalize= True).loc['China']

SocialMedia
WeChat 微信                   0.682578
YouTube                     0.088305
Weibo 新浪微博                  0.071599
Twitter                     0.042959
I don't use social media    0.040573
Reddit                      0.021480
LinkedIn                    0.019093
Instagram                   0.009547
Youku Tudou 优酷              0.009547
Facebook                    0.007160
WhatsApp                    0.004773
VK ВКонта́кте               0.002387
Name: proportion, dtype: float64

In [48]:
country_grp['SocialMedia'].value_counts(normalize= True).loc['India']

SocialMedia
WhatsApp                    0.343102
YouTube                     0.209035
LinkedIn                    0.108808
Facebook                    0.098122
Instagram                   0.092455
Twitter                     0.062014
Reddit                      0.054080
I don't use social media    0.028012
Snapchat                    0.002429
VK ВКонта́кте               0.000648
Hello                       0.000486
WeChat 微信                   0.000486
Weibo 新浪微博                  0.000162
Youku Tudou 优酷              0.000162
Name: proportion, dtype: float64

In [49]:
country_grp['SocialMedia'].value_counts(normalize= True).loc['Germany']

SocialMedia
WhatsApp                    0.254688
YouTube                     0.176563
Reddit                      0.170313
Twitter                     0.157812
I don't use social media    0.093490
Facebook                    0.072656
Instagram                   0.047656
LinkedIn                    0.022656
Snapchat                    0.001823
VK ВКонта́кте               0.001302
WeChat 微信                   0.001042
Name: proportion, dtype: float64

In [51]:
df.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq',
       'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge',
       'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests',
       'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [52]:
country_grp['ConvertedComp'].median().loc['India']

np.float64(10080.0)

In [53]:
country_grp['ConvertedComp'].median().loc['Germany']

np.float64(61872.0)

In [57]:
country_grp['ConvertedComp'].agg(['median', 'mean'])

                                        median           mean
Country
Afghanistan                             4464.0   20312.727273
Albania                                11040.0   25471.676471
Algeria                                 6096.0    7386.518519
Andorra                               171862.0  171862.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    9600.0   18606.838710
Viet Nam                               11892.0   18145.875000
Yemen                                  11940.0   10164.000000
Zambia                                  8823.5   12989.166667
Zimbabwe                               16500.0   33090.000000

[177 rows x 2 columns]

In [58]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Germany']

median     61872.000000
mean      108449.673264
Name: Germany, dtype: float64

In [64]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

2187

In [65]:
country_grp['LanguageWorkedWith'].apply( lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              5
Albania                                 17
Algeria                                 21
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    20
Viet Nam                                59
Yemen                                    2
Zambia                                   2
Zimbabwe                                13
Name: LanguageWorkedWith, Length: 177, dtype: int64

In [66]:
country_respondent = df['Country'].value_counts()
country_respondent

Country
United States                       14723
India                                6395
Germany                              4131
United Kingdom                       4000
Canada                               2357
                                    ...
Saint Kitts and Nevis                   1
Malawi                                  1
Liberia                                 1
Saint Vincent and the Grenadines        1
San Marino                              1
Name: count, Length: 177, dtype: int64

In [68]:
country_uses_python = country_grp['LanguageWorkedWith'].apply( lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              5
Albania                                 17
Algeria                                 21
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    20
Viet Nam                                59
Yemen                                    2
Zambia                                   2
Zimbabwe                                13
Name: LanguageWorkedWith, Length: 177, dtype: int64

In [70]:
python_df = pd.concat([country_respondent, country_uses_python], axis = 'columns', sort = False)
python_df

                                  count  LanguageWorkedWith
Country
United States                     14723                7095
India                              6395                2187
Germany                            4131                1720
United Kingdom                     4000                1651
Canada                             2357                1108
...                                 ...                 ...
Saint Kitts and Nevis                 1                   0
Malawi                                1                   0
Liberia                               1                   0
Saint Vincent and the Grenadines      1                   0
San Marino                            1                   1

[177 rows x 2 columns]

In [72]:
python_df.rename(columns={'Country':'NumRespondent', 'LanguageWorkedWith': "NumKnowPython"}, inplace = True)
python_df

                                  count  NumKnowPython
Country
United States                     14723           7095
India                              6395           2187
Germany                            4131           1720
United Kingdom                     4000           1651
Canada                             2357           1108
...                                 ...            ...
Saint Kitts and Nevis                 1              0
Malawi                                1              0
Liberia                               1              0
Saint Vincent and the Grenadines      1              0
San Marino                            1              1

[177 rows x 2 columns]

In [76]:
python_df['PercentKnowPython'] = (python_df['NumKnowPython']/python_df['count'] * 100)
python_df

                                  count  NumKnowPython  PercentKnowPython
Country
United States                     14723           7095          48.189907
India                              6395           2187          34.198593
Germany                            4131           1720          41.636408
United Kingdom                     4000           1651          41.275000
Canada                             2357           1108          47.008910
...                                 ...            ...                ...
Saint Kitts and Nevis                 1              0           0.000000
Malawi                                1              0           0.000000
Liberia                               1              0           0.000000
Saint Vincent and the Grenadines      1              0           0.000000
San Marino                            1              1         100.000000

[177 rows x 3 columns]

In [79]:
python_df.sort_values(by = 'PercentKnowPython', ascending=False, inplace=True)
python_df.head(50)

                             count  NumKnowPython  PercentKnowPython
Country
San Marino                       1              1         100.000000
Timor-Leste                      1              1         100.000000
Niger                            1              1         100.000000
Dominica                         1              1         100.000000
Turkmenistan                     6              5          83.333333
Congo, Republic of the...        5              4          80.000000
Benin                            4              3          75.000000
Uganda                          48             32          66.666667
Bahamas                          3              2          66.666667
Guinea                           3              2          66.666667
Guyana                           3              2          66.666667
Maldives                         8              5          62.500000
Namibia                          5              3          60.000000
Iceland                         35             20          57.142857
Republic of Korea               28             15          53.571429
United Republic of Tanzania     19             10          52.631579
South Korea                    107             56          52.336449
Monaco                           2              1          50.000000
Angola                           4              2          50.000000
Mali                             2              1          50.000000
Mauritania                       4              2          50.000000
Oman                             8              4          50.000000
Sierra Leone                     2              1          50.000000
Bhutan                           2              1          50.000000
Liechtenstein                    2              1          50.000000
Haiti                            4              2          50.000000
Mongolia                        14              7          50.000000
Chile                          145             72          49.655172
Finland                        390            192          49.230769
Ecuador                         60             29          48.333333
United States                14723           7095          48.189907
Japan                          266            128          48.120301
Kenya                          169             81          47.928994
Hong Kong (S.A.R.)             132             63          47.727273
Cuba                            21             10          47.619048
Canada                        2357           1108          47.008910
China                          466            217          46.566524
Switzerland                    695            323          46.474820
Luxembourg                      39             18          46.153846
Israel                         674            310          45.994065
Taiwan                         135             62          45.925926
Thailand                       147             66          44.897959
France                        1694            756          44.628099
Estonia                        122             54          44.262295
Nepal                          161             71          44.099379
Iraq                            25             11          44.000000
Singapore                      218             95          43.577982
Denmark                        424            183          43.160377
Ghana                           63             27          42.857143
Kyrgyzstan                      14              6          42.857143

In [80]:
python_df.loc['Japan']

count                266.000000
NumKnowPython        128.000000
PercentKnowPython     48.120301
Name: Japan, dtype: float64