In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('/results.csv', on_bad_lines='skip', index_col='Respondent')
schema_df = pd.read_csv('/schema.csv',index_col='Column')

In [18]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [19]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [20]:
df.sort_values(by= ['Country', 'ConvertedComp'], ascending=[True, False], inplace = True)
df.head(50)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
63129,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, full-time",I never completed any formal education,NaN,Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",NaN,Less than 1 year,Younger than 5 years,1,Very dissatisfied,Very dissatisfied,Very confident,Yes,Yes,I am actively looking for a job,I've never had a job,Write any code,Yes,How widely used or impactful my work output wo...,I had a negative experience or interaction at ...,AED,United Arab Emirates dirham,648838511.0,Monthly,1000000.0,168.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work,It's complicated,"Other place, such as a coworking space or cafe",Far below average,No,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;Other(s):,Bash/Shell/PowerShell;TypeScript,MySQL,MySQL,Android;iOS;Windows;WordPress;Other(s):,Android;iOS;Windows;WordPress;Other(s):,Angular/Angular.js;Express;jQuery;Laravel;Othe...,Angular/Angular.js;Express;jQuery;Laravel;Othe...,Ansible;Apache Spark;Torch/PyTorch,Apache Spark;Torch/PyTorch,Android Studio;Atom;Coda;Eclipse;Emacs;IPython...,Windows,"Outside of work, for personal projects",Accepting Bitcoin or other coins and tokens as...,Useful across many domains and could change ma...,Yes,Yes,Yes,I don't use social media,Online,UserID,NaN,I have never visited Stack Overflow (before to...,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,0-10 minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...",NaN,"No, not at all",NaN,Tech articles written by other developers,NaN,NaN,NaN,NaN,NaN,Yes,Too short,Easy
50499,"I am not primarily a developer, but I write co...",Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A health science (ex. nursing, pharmacy, radio...",Participated in a full-time developer training...,"10,000 or more employees",Data or business analyst;Database administrato...,7,27,7,Very dissatisfied,Very dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",More than 4 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Opportunities for professional development;Div...,"Something else changed (education, award, medi...",AFN,Afghan afghani,960000.0,Monthly,153216.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Time spent com...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have a great deal of influence,C#;HTML/CSS;JavaScript;SQL;VBA,C#;HTML/CSS;JavaScript;R;SQL;TypeScript;VBA,Microsoft SQL Server;PostgreSQL;SQLite,MariaDB;MongoDB;Microsoft SQL Server;PostgreSQ...,NaN,Android,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery;React.js;Vue.js,.NET,.NET;.NET Core;Node.js;Xamarin,Visual Studio,Windows,I do not use containers,Implementing our own cryptocurrency,NaN,Yes,Yes,Yes,WhatsApp,Online,Login,2013,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,NaN,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
39258,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Database administrator;Designer;Developer, bac...",2,22,1,Very satisfied,Very satisfied,Very confident,No,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",AFN,Afghan afghani,120000.0,Monthly,19152.0,49.0,There is a schedule and/or spec (made by me or...,Not enough people for the workload;Time spent ...,Less than once per month / Never,Office,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have some influence,HTML/CSS;JavaScript;PHP;SQL;TypeScript,C#;Dart;JavaScript;SQL;TypeScript,MariaDB;MongoDB;MySQL;PostgreSQL,Couchbase;Firebase;MariaDB;MongoDB;Redis,Android;AWS;Linux;Windows;WordPress,Android;AWS;Docker;Heroku;iOS;Linux;Raspberry ...,Angular/Angular.js;Drupal;Express;Laravel,Angular/Angular.js;Drupal;Express,Cordova;Node.js,Hadoop;Node.js,Notepad++;PHPStorm;Vim;Visual Studio Code,Linux-based,Production,NaN,NaN,Yes,Yes,No,Facebook,Online,Login,2016,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,Yes,NaN,"Yes, somewhat",NaN,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,East Asian;South Asian,Yes,Too long,Easy
58450,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",6,20,2,Neither satisfied nor dissatisfied,Slightly satisfied,Very confident,Yes,Yes,I am actively looking for a job,1-2 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,"Languages, frameworks, and other technologies ...",I had a negative experience or interaction at ...,AFN,Afghan afghani,110000.0,Monthly,17556.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment,It's complicated,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have little or no influence,Assembly;C;C++;HTML/CSS;Java;PHP;SQL,C;C++;HTML/CSS;Java;JavaScript;SQL;TypeScript,MySQL;PostgreSQL,MySQL;PostgreSQL,Linux;Windows,Windows,NaN,Spring,NaN,Node.js,IntelliJ;Notepad++,Windows,Development,Accepting Bitcoin or other coins and tokens as...,Useful for immutable record keeping outside of...,Yes,Yes,Yes,Facebook,Online,Handle,NaN,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech articles written by other developers,26.0,Man,No,Straight / Heterosexual,South Asian,No,Too long,Neither easy nor difficult
7085,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, full-stack",7,19,6,Slightly dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,AFN,Afghan afghani,90000.0,Monthly,14364.0,30.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Lack of s...,About half the time,Office,Average,"Yes, because I see value in code review",3.0,NaN,NaN,NaN,HTML/CSS;JavaScript;PHP,JavaScript;Kotlin;PHP,MySQL,MongoDB;MySQL;Redis,Linux;MacOS;Other(s):,Linux;MacOS;Other(s):,jQuery;Laravel;Vue.js,ASP.NET;jQuery;Laravel;Vue.js,NaN,React Native,Sublime Text;Visual Studio Code,MacOS,"Development;Outside of work, for personal proj...",NaN,NaN,Yes,Also Yes,Yes,Instagram,Online,UserID,2016,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're intere...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult
22450,I am a developer by profession,No,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Developer, desktop or ente...",3,19,2,Very satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,Office environment or company culture;Opportun...,I heard about a job opportunity (from a recrui...,AFN,Afghan afghani,50000.0,Monthly,7980.0,45.0,There's no schedule or spec; I work on what se...,Distracting work environment;Lack of support f...,Less than once per month / Never,Home,A little above average,"Yes, because I see value in code review",3.0,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,C#;HTML/CSS;Java;JavaScript;PHP;TypeScript,C#;Dart;HTML/CSS;Java;JavaScript;Kotlin;PHP;Ty...,Firebase;MongoDB;MySQL,Firebase;MongoDB;MySQL,Android;Linux;Windows;WordPress,Docker;Linux;Windows,Angular/Angular.js;ASP.NET;Express;Laravel;Vue.js,Angular/Angular.js;Express;Laravel;React.js;Sp...,Node.js,Flutter;Node.js;React Native,Visual Studio Code,Windows,Development,NaN,NaN,NaN,Yes,What?,Facebook,In real life (in person),Login,2019,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,24.0,Man,No,NaN,Middle Eastern,Yes,Too long,Neither easy nor difficult
48436,I am a developer by profession,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Afghanistan,"Yes, part-time","Secondary school (e.g. American high school, G...",NaN,Taken a part-time in-person course in programm...,10 to 19 employees,"Database administrator;Designer;Developer, bac...",2,20,1,Slightly dissatisfied,Slightly dissatisfied,Very confident,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,AFN,Afghan afghani,28000.0,Monthly,4464.0,45.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Lack of s...,It's complicated,Office,A little above average,"Yes, because I was told to do so",10.0,"No, but I think we should",Not sure,I have little or no influence,C#;HTML/CSS;JavaScript;PHP,HTML/CSS;JavaScript;PHP;Python,Firebase;MySQL,Firebase;MySQL,Android;Windows;WordPress,Android;Windows;WordPress,Angular/Angular.js;jQuery;Laravel;React.js;Vue.js,Angular/Angular.js;jQuery;Laravel,.NET Core;Node.js;React Native,Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,Development,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Facebook,Online,Username,2017,Multiple times per day,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per week,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,No,Too long,Neither easy nor difficult
10746,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken a part-time in-person course in programm...,100 to 499 employees,"Developer, back-end",4,20,1,Slightly dissatisfied,Slightly dissatisfied,Very confident,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",AFN,Afghan afghani,25000.0,Monthly,3996.0,40.0,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Lack of s...,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,HTML/CSS;Java;JavaScript;PHP;Python;SQL,HTML/CSS;JavaScript;Python,Microsoft SQL Server;MySQL;PostgreSQL,Firebase;MongoDB;Oracle,Android;Linux;Windows,Android;iOS;Linux;Raspberry Pi,Angular/Angular.js;ASP.NET;Laravel,Angular/Angular.js;Django;React.js;Vue.js,Apache Spark;.NET;Node.js,Node.js,Android Studio;Eclipse;PyCharm;Visual Studio Code,Linux-based,I do not use containers,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,YouTube,Neither,Login,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Not sure,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Neither easy nor difficult
8149,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Afghanistan,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Participated in a full-time developer training...,2-9 employees,"Developer, back-end",2,19,1,Slightly dissatisfied,Slightly dissatisfied,Very confident,Yes,Yes,I am actively looking for a job,Less than a year ago,Interview with people in senior / management r...,NaN,Office environment or company culture,"My job status changed (promotion, new job, etc.)",AFN,Afghan afghani,10000.0,Monthly,1596.0,50.0,There is a schedule and/or spec (made by me or...,Meetings,All or almost all the time (I'm full-time remote),Office,A little above average,"Yes, because I was told to do so",6.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have some influence,HTML/CSS;Java;PHP;SQL,NaN,MySQL,NaN,Android;Linux;Windows,NaN,Laravel;Spring,NaN,NaN,NaN,Android Studio;Eclipse;NetBeans;Notepad++;Visu...,Linux-based,NaN,Implementing cryptocurrency-based products,An irresponsible use of resources,Yes,Yes,Yes,Facebook,Online,UserID,2008,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...",Yes,"Yes, definitely",Just as welcome now as I felt last year,NaN,24.0,Man,Yes,Bisexual,South Asian,Yes,Too long,Easy
29736,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, part-time",Primary/elementary school,NaN,Taken an online course in programming or softw...,20 to 99 employees,Student,10,11,3,Slightly satisfied,Very satisfied,Somewhat confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Complete a take-home project;Interview with pe...,Yes,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,AFN,Afghan afghani,7000.0,Monthly,1116.0,36.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Lack of support f...,"Less than half the time, but at least one day ...",Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the deve...",Developers and management have nearly equal in...,I have some influence,Assembly;C;C++;C#;Java;Kotlin;VBA,C;C++;HTML/CSS;JavaScript;PHP;TypeScript,SQLite,MySQL;SQLite,Android;Windows,WordPress,NaN,Angular/Angular.js,React Native;Unity 3D,React Native;Unreal Engine,Android Studio;NetBeans;Visual Studio Code,Windows,I do not use containers,Not at all,An irresponsible use of resources,No,Yes,Yes,NaN,NaN,UserID,2017,Multiple times per day,Find answers to specific questions,6-10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Multiple times per day,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Courses on technologies you're interested in,26.0,Man,No,NaN,NaN,Yes,Too long,Easy
722,I am a developer by profession,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,NaN,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,Less than 1 year,Younger than 5 years,Less than 1 year,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,NaN,No,NaN,I heard about a job opportunity (from a recrui...,AFN,Afghan afghani,1.0,Yearly,0.0,1.0,NaN,NaN,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",1.0,"No, and I'm glad we don't",NaN,I have little or no influence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,SIGH,What?,NaN,Neither,NaN,2008,Multiple times per day,NaN,More than 10 times per week,The other resource was much faster,60+ minutes,Not sure / can't remember,NaN,Yes,Yes,Not sure,Not applicable - I did not use Stack Overflow ...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult

In [23]:
df[['Country', 'ConvertedComp']].head(50)

                Country  ConvertedComp
Respondent
63129       Afghanistan      1000000.0
50499       Afghanistan       153216.0
39258       Afghanistan        19152.0
58450       Afghanistan        17556.0
7085        Afghanistan        14364.0
22450       Afghanistan         7980.0
48436       Afghanistan         4464.0
10746       Afghanistan         3996.0
8149        Afghanistan         1596.0
29736       Afghanistan         1116.0
722         Afghanistan            0.0
28638       Afghanistan            0.0
6417        Afghanistan            NaN
7353        Afghanistan            NaN
12310       Afghanistan            NaN
26340       Afghanistan            NaN
29045       Afghanistan            NaN
33178       Afghanistan            NaN
37802       Afghanistan            NaN
40000       Afghanistan            NaN
43106       Afghanistan            NaN
44403       Afghanistan            NaN
45854       Afghanistan            NaN
47110       Afghanistan            NaN
49702       Afghanistan            NaN
50767       Afghanistan            NaN
51859       Afghanistan            NaN
58760       Afghanistan            NaN
59560       Afghanistan            NaN
60569       Afghanistan            NaN
60946       Afghanistan            NaN
62168       Afghanistan            NaN
62525       Afghanistan            NaN
74386       Afghanistan            NaN
80926       Afghanistan            NaN
85715       Afghanistan            NaN
85825       Afghanistan            NaN
86362       Afghanistan            NaN
86932       Afghanistan            NaN
87091       Afghanistan            NaN
88582       Afghanistan            NaN
88731       Afghanistan            NaN
2782        Afghanistan            NaN
63019       Afghanistan            NaN
38308           Albania       187668.0
3787            Albania       114550.0
9270            Albania        74474.0
6716            Albania        60000.0
10303           Albania        57300.0
66280           Albania        41244.0

In [24]:
df.nsmallest(10, 'ConvertedComp')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
722,I am a developer by profession,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,NaN,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,Less than 1 year,Younger than 5 years,Less than 1 year,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,NaN,No,NaN,I heard about a job opportunity (from a recrui...,AFN,Afghan afghani,1.0,Yearly,0.0,1.0,NaN,NaN,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",1.0,"No, and I'm glad we don't",NaN,I have little or no influence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,SIGH,What?,NaN,Neither,NaN,2008,Multiple times per day,NaN,More than 10 times per week,The other resource was much faster,60+ minutes,Not sure / can't remember,NaN,Yes,Yes,Not sure,Not applicable - I did not use Stack Overflow ...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
28638,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,NaN,NaN,NaN,36,13,16,Very dissatisfied,Very dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NaN,NaN,NaN,NaN,NaN,AFN,Afghan afghani,3.0,Monthly,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,MySQL;SQLite,MySQL;SQLite,Android;iOS;Linux;MacOS,Android;iOS;Linux,jQuery,NaN,TensorFlow;Unity 3D,Hadoop;TensorFlow;Unity 3D,Emacs,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,No,NaN,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,6-10 times per week,The other resource was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","No, not at all",A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN
13825,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,NaN,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,13,83,Less than 1 year,Very dissatisfied,Very satisfied,NaN,NaN,NaN,I am actively looking for a job,NA - I am an independent contractor or self em...,Complete a take-home project;Solve a brain-tea...,Yes,Financial performance or funding status of the...,"Something else changed (education, award, medi...",AFN,Afghan afghani,1.0,Yearly,0.0,168.0,NaN,Being tasked with non-development work;Non-wor...,About half the time,Home,Far above average,No,NaN,"Yes, it's part of our process",NaN,I have a great deal of influence,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,NaN,NaN,I do not use containers,NaN,An irresponsible use of resources,No,Yes,Yes,NaN,Neither,NaN,2015,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",A lot less welcome now than last year,NaN,56.0,NaN,NaN,NaN,NaN,Yes,Too short,Easy
40913,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Armenia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, desktop or enterprise applications;...",7,15,4,Slightly satisfied,Slightly satisfied,Very confident,Not sure,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",AMD,Armenian dram,0.0,Monthly,0.0,40.0,There's no schedule or spec; I work on what se...,"Meetings;Non-work commitments (parenting, scho...","Less than half the time, but at least one day ...",Office,A little above average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;C;C++;Java;JavaScript;Py...,C;C++;Java;Python;SQL;TypeScript,Elasticsearch;MariaDB;MongoDB;MySQL;Redis,MariaDB;MongoDB;MySQL,Arduino;AWS;Docker;Linux;MacOS;Raspberry Pi;Sl...,Arduino;Linux;MacOS;Raspberry Pi,ASP.NET;Django;Flask,Django;Flask,.NET;Node.js;TensorFlow;Torch/PyTorch,Node.js,IntelliJ;IPython / Jupyter;Sublime Text;Vim,Linux-based,Production,Not at all,A passing fad,No,SIGH,Yes,Facebook,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers,22.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
30630,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,2-9 employees,"Database administrator;Developer, back-end;Dev...",35,7,30,Neither satisfied nor dissatisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,Interview with people in peer roles;Interview ...,No,Industry that I'd be working in;Office environ...,I heard about a job opportunity (from a recrui...,AUD,Australian dollar,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Distracting work environment;Non-work commitme...,It's complicated,"Other place, such as a coworking space or cafe",A little above average,"Yes, because I see value in code review",10.0,"No, but I think we should",NaN,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Ruby,Elixir;Ruby;TypeScript,PostgreSQL,PostgreSQL,AWS;iOS,Android;AWS;iOS,Ruby on Rails;Vue.js,Ruby on Rails;Vue.js,Chef;React Native,React Native,Sublime Text;TextMate;Vim;Xcode,MacOS,I do not use containers,Not at all,An irresponsible use of resources,Yes,"Fortunately, someone else has that title",No,Reddit,Online,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",A lot less welcome now than last year,NaN,43.0,NaN,No,NaN,NaN,No,Appropriate in length,Easy
69049,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,2-9 employees,"Developer, full-stack;Engineering manager",17,12,14,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",AUD,Australian dollar,0.0,Yearly,0.0,25.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Time spent com...,All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",1.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C#;Go;HTML/CSS;JavaScr...,Dart;Elixir;JavaScript;Kotlin;Python;R;Ruby;Rust,PostgreSQL;SQLite,Cassandra;PostgreSQL;Redis,Android;Arduino;Google Cloud Platform;iOS;Linu...,Google Cloud Platform;Heroku;Kubernetes;Linux;...,Ruby on Rails,Ruby on Rails;Vue.js,.NET;React Native,Ansible;Flutter;Hadoop;Pandas;React Native,IntelliJ;Visual Studio;Visual Studio Code;Xcode,MacOS,Production,NaN,A passing fad,No,Also Yes,Yes,Reddit,In real life (in person),Username,2008,A few times per week,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",Just as welcome now as I felt last year,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
19340,"I am not primarily a developer, but I write co...",Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",NaN,Austria,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Fine arts or performing arts (ex. graphic desi...,Taken an online course in programming or softw...,NaN,NaN,10,20,5,Neither satisfied nor dissatisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in peer roles;Interview ...,No,Office environment or company culture;Opportun...,I was preparing for a job search,CHF,Swiss franc,0.0,Monthly,0.0,35.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,Average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have a great deal of influence,Assembly;C;Elixir;HTML/CSS;Java;JavaScript;Pyt...,Clojure,PostgreSQL;SQLite,NaN,Arduino;Raspberry Pi,Arduino;Raspberry Pi,Other(s):,Other(s):,NaN,NaN,IntelliJ;Sublime Text,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful for immutable record keeping outside of...,No,Also Yes,Yes,NaN,In real life (in person),Username,2010,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,32.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
16214,"I am not primarily a developer, but I write co...",Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",NaN,20 to 99 employees,"Engineer, data;Engineering manager;Product man...",20,16,20,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Interview with people in peer roles,No,Financial performance or funding status of the...,I was preparing for a job search,EUR,European Euro,0.0,Yearly,0.0,10.0,There's no schedule or spec; I work on what se...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,No,NaN,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Java;PHP;Other(s):,Java;PHP;Other(s):,MariaDB;MySQL,MariaDB;MySQL,Android;Linux;Raspberry Pi;Windows;WordPress,Android;Linux;Raspberry Pi;Windows;WordPress,jQuery;Spring,jQuery;Spring,NaN,NaN,Android Studio;Eclipse;IntelliJ;NetBeans,Linux-based,I do not use containers,Not at all,NaN,No,Yes,What?,WhatsApp,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,99.0,NaN,No,NaN,NaN,NaN,Too long,Easy
29355,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Bosnia and Herzegovina,"Yes, part-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","Just me - I am a freelancer, sole proprietor, ...",NaN,10,10,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,Less than a year ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Specific depar...,"Something else changed (education, award, medi...",BAM,Bosnia and Herzegovina convertible mark,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Inadequ...,It's complicated,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Python;Ruby;Other(s):,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;Oth...,NaN,NaN,Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows,Android;Arduino;AWS;iOS;Linux;MacOS;Raspberry ...,NaN,NaN,Pandas;TensorFlow;Torch/PyTorch;Unity 3D;Unrea...,.NET;Torch/PyTorch;Unity 3D,Android Studio;Emacs;PyCharm;Visual Studio;Vis...,Linux-based,I do not use containers,NaN,A passing fad,Yes,Also Yes,Yes,YouTube,In real life (in person),Username,2013,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,NaN,No,NaN,NaN,NaN,Too long,Easy
1685,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Brazil,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...","Designer;Developer, full-stack;Developer, game...",8,16,3,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Specific department or team I'd be working on;...,I was preparing for a job search,BRL,Brazilian real,0.0,Monthly,0.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Toxic wo...,All or almost all the time (I'm full-time remote),Home,Average,"Yes, because I see value in code review",6.0,NaN,NaN,NaN,Elixir;HTML/CSS;JavaScript;PHP;Python,C#;Kotlin;Python,Cassandra;MariaDB;MongoDB;PostgreSQL,Cassandra;MariaDB;MongoDB;PostgreSQL,Docker;Kubernetes;MacOS,Android;Linux;Windows,Laravel,Django;Flask;Laravel;Vue.js,Node.js,.NET;Node.js;Unity 3D;Other(s):,Android Studio;PHPStorm;PyCharm;Visual Studio ...,Windows,Development,NaN,Useful across many domains and could change ma...,No,Yes,Yes,WhatsApp,In real life (in person),NaN,2010,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Neither easy nor difficult

In [25]:
df['ConvertedComp'].nlargest(10)

Respondent
25983    2000000.0
87896    2000000.0
22013    2000000.0
28243    2000000.0
72732    2000000.0
78151    2000000.0
80200    2000000.0
52132    2000000.0
75561    2000000.0
32250    2000000.0
Name: ConvertedComp, dtype: float64