In [7]:
import pandas as pd

data = {
    "Name": ["Aman", "Ravi", "Aman", None],
    "Marks": [85, None, 90, 75],
    "City": ["Delhi", "Mumbai", "Delhi", "Delhi"]
}

df = pd.DataFrame(data)
df

   Name  Marks    City
0  Aman   85.0   Delhi
1  Ravi    NaN  Mumbai
2  Aman   90.0   Delhi
3  None   75.0   Delhi

In [8]:
df.isnull()

    Name  Marks   City
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False  False

In [9]:
df.notnull()

    Name  Marks  City
0   True   True  True
1   True  False  True
2   True   True  True
3  False   True  True

In [10]:
df.dropna()

   Name  Marks   City
0  Aman   85.0  Delhi
2  Aman   90.0  Delhi

In [11]:
df.dropna(axis=1)

     City
0   Delhi
1  Mumbai
2   Delhi
3   Delhi

In [12]:
df.fillna("unknown")

      Name    Marks    City
0     Aman     85.0   Delhi
1     Ravi  unknown  Mumbai
2     Aman     90.0   Delhi
3  unknown     75.0   Delhi

In [14]:
df["Marks"].fillna(df["Marks"].mean())

0    85.000000
1    83.333333
2    90.000000
3    75.000000
Name: Marks, dtype: float64

In [16]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [17]:
df.duplicated(subset=["Name"])

0    False
1    False
2     True
3    False
dtype: bool

In [18]:
df.drop_duplicates()

   Name  Marks    City
0  Aman   85.0   Delhi
1  Ravi    NaN  Mumbai
2  Aman   90.0   Delhi
3  None   75.0   Delhi

In [19]:
df.drop_duplicates(subset = ["Name"])

   Name  Marks    City
0  Aman   85.0   Delhi
1  Ravi    NaN  Mumbai
3  None   75.0   Delhi

In [20]:
df.head()

   Name  Marks    City
0  Aman   85.0   Delhi
1  Ravi    NaN  Mumbai
2  Aman   90.0   Delhi
3  None   75.0   Delhi

In [22]:
df["Marks"] = df["Marks"].astype(float)

In [26]:
df.groupby("City")["Marks"].mean()

City
Delhi     83.333333
Mumbai          NaN
Name: Marks, dtype: float64

In [27]:
df.groupby("City")["Marks"].count()

City
Delhi     3
Mumbai    0
Name: Marks, dtype: int64

In [28]:
df.groupby("City").agg({
    "Marks": ["mean", "sum", "count"]
})

            Marks
             mean    sum count
City
Delhi   83.333333  250.0     3
Mumbai        NaN    0.0     0